version: "3"

services:
  sss-track-session-number_activity-name:
    build: .
    environment:
      - "DB_USERNAME="
      - "DB_PASSWORD="
      - "DB_HOST=sss-track-session-number_activity-name-db"
      - "DB_NAME="
    ports:
      - "8010:80"
    volumes:
      - ../src:/var/www/html
    depends_on:
      - "sss-track-session-number_activity-name-db"
    restart: unless-stopped

  sss-track-session-number_activity-name-db:
    image: mariadb:10.1
    environment:
      - "MYSQL_ROOT_PASSWORD="
      - "MYSQL_DATABASE="
    restart: unless-stopped
